

export const data = [
    {
        id: 1,
        image: "trendCard1.jpg",
        description: "Я женился на однокласснице,...",
        author: "Amano Seiju",
        rating: 7.52,
        views: 567,
    },
    {
        id: 2,
        image: "trendCard2.jpg",
        description: "Да, я паук, и что с того?",
        author: "Baba Okina",
        rating: 8.62,
        views: 7377,
    },
    {
        id: 3,
        image: "trendCard3.jpg",
        description: "Я, Архидемон, взял эльфийку-р...",
        author: "Teshima Fuminori",
        rating: 7.7,
        views: 4567,
    },
    {
        id: 4,
        image: "trendCard4.jpg",
        description: "Нет игры - нет жизни",
        author: "Kamiya Yuu",
        rating: 8.85,
        views: 637,
    },
    {
        id: 5,
        image: "trendCard5.jpg",
        description: "Добро пожаловать в кл...",
        author: "Kinugasa Shougo",
        rating: 9.52,
        views: 265,
    },
    {
        id: 6,
        image: "trendCard6.jpg",
        description: "О моем перерождении в...",
        author: "Fuse",
        rating: 7.84,
        views: 123,
    },
    {
        id: 7,
        image: "trendCard7.jpg",
        description: "Я нашел 100 Миллионов в Мо...",
        author: "Cuttlefish That Loves Diving",
        rating: 8.07,
        views: 234,
    },
    {
        id: 8,
        image: "trendCard7.jpg",
        description: "Я нашел 100 Миллионов в Мо...",
        author: "Cuttlefish That Loves Diving",
        rating: 8.07,
        views: 234,
    },
]